export const PRODUCTLIST_FETCH_START = "PRODUCTLIST_FETCH_START";
export const PRODUCTLIST_FETCH_SUCCESS = "PRODUCTLIST_FETCH_SUCCESS";
export const PRODUCTLIST_FETCH_ERROR = "PRODUCTLIST_FETCH_ERROR";

export const PRODUCT_DETAILS_FETCH_START = "PRODUCT_DETAILS_FETCH_START";
export const PRODUCT_DETAILS_FETCH_SUCCESS = "PRODUCT_DETAILS_FETCH_SUCCESS";
export const PRODUCT_DETAILS_FETCH_ERROR = "PRODUCT_DETAILS_FETCH_ERROR";

export const PRODUCTLIST_FEATURED_FETCH_START =
  "PRODUCTLIST_FEATURED_FETCH_START";
export const PRODUCTLIST_FEATURED_FETCH_SUCCESS =
  "PRODUCTLIST_FEATURED_FETCH_SUCCESS";
export const PRODUCTLIST_FEATURED_FETCH_ERROR =
  "PRODUCTLIST_FEATURED_FETCH_ERROR";
